### PR TITLE
Update Go version and use Go mod 

### LINKED ISSUE #440: Migrate from godep to gomod and update go version
@jcmoraisjr As we spoke earlier, this is a tech dept :)

We need to upgrade go version and move to gomod to follow some recommended best practices :)

I'm dealing (and suffering) with it, and registering this as an issue to someone else who wants to follow the work

### PR DESCRIPTION
**Pull request by rikatz**
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@serpro.gov.br>

This commit deals with two improvements for future releases:

* Update to Go 1.13.4
* Migrate from Godep to built-in go mod
* ~Upgrade Kubernetes modules to 1.15.5~ -> Moved to #441 

Fixes #440

### CODE REVIEW

**Comment by rikatz** [comment]
Some comments to follow the PR:

* Removed, by now the pkg/common/net/ssl/ssl_test.go as it uses a 'triple' package which was removed from client-go. Need to rewrite this test, a suggestion is to copy it from ingress-nginx as it's almost the same thing (giving also the right credits to them)

* Removed any reference to import 'k8s.io/kubernetes' and changed it to 'k8s.io/api' which is the right import. -> pkg/common/ingress/status/status_test.go and pkg/common/ingress/controller/backend_ssl_test.go

* In store/main.go removed ``k8s.io/kubernetes/pkg/util/node`` and added a const ``const nodeUnreachablePodReason = "NodeLost"`` to replace this call, as this was the only reference to node package

The commits that will follow will adapt the ingress to use the latest client-go version

**Comment by rikatz** [comment]
* In pkg/common/k8s/main.go -> Replace all kubeClient.Core() to kubeClient.CoreV1()

* In plg/common/ingress/status/status.go -> Replace all client.Extensions().Ingresses client.ExtensionsV1beta1().Ingresses

**Comment by rikatz** [comment]
A lot of new changes here:

* Upgraded to client-go for kubernetes 1.15.5

* Changed the leader election process from channels to context, as required by the new client-go (may the force be with us on this!)

**Comment by rikatz** [comment]
Kubernetes Client upgrade moved to https://github.com/jcmoraisjr/haproxy-ingress/issues/441

**Comment by jcmoraisjr** [comment]
Merging, thanks!

**Pull request merged**
