### PR TITLE
503 server to respond to 127.0.0.1:8181 backends

### PR DESCRIPTION
**Pull request by from-nibly**
create a 503 frontend/backend to respond to the default backends that are sent by the ingress library.

### CODE REVIEW

**Comment by jcmoraisjr** [comment]
Sorry the delay. What's the purpose of this PR?

**Comment by from-nibly** [comment]
The ingress library returns a bunch of `Backend`s that have a remote host and port of `127.0.0.1:8181`. This comes from `nginx-ingress-controllers` implementation of having a server that listens on that port and only returns 503s. So when there is a kubernetes service with no `address`s in the `Endpoints` object it sets the upstream to the 503 server and nginx returns a 503. Currently (without this pr) the `haproxy-ingress` project still sends requests to `127.0.0.1:8181` but gets a connection refused. This actually ends up with a response with status 503 but when logged shows that it got a connection refused. Adding this server will define a distinction between not having any `address`s on the `Endpoints` and getting a connection refused for some other reason.

**Comment by jcmoraisjr** [comment]
Sure, logging, makes sense. A few suggestions:

* Create just a `listen` section below the `error413`
* What about use a `http-request deny deny_status 503` instead of using an external file?

**Comment by from-nibly** [comment]
The advantage of having the file is that it allows us to post a reason in the html. Is there a way to do that with the inline solution?

**Comment by jcmoraisjr** [comment]
I wasn't taking into account a reason to the end user. Do you have such requirement? Internal logs is another matter and should be fixed.

**Comment by from-nibly** [comment]
we are using this for testing so 503s because a service isn't up yet can happen all the time. it would be nice if we could let the user know that is the reason.

**Comment by jcmoraisjr** [comment]
Lets give it a try. Another few changes:

* Move to `/usr/local/etc/haproxy/errors/` where all HAProxy stuff (except template and cfg) is located
* Rename the `listen` section to `error503noendpoints` in order to mimic the http filename
* Add a line break at the end of the http file and convert it to CRLF as suggested in the HAProxy [docs](http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4-errorfile)

**Comment by from-nibly** [comment]
@jcmoraisjr changes have been made

**Comment by jcmoraisjr** [comment]
Missing change to the new path in the template.

**Comment by from-nibly** [comment]
whoops. right you are. Changed and tested

**Comment by jcmoraisjr** [comment]
Thanks

**Pull request merged**
