### PR TITLE
Allow signer to work with wildcard dns certs

### PR DESCRIPTION
**Pull request by pbabilas**
As in topic, this pr allows acme signer to work with wildcard dns in cert.
Instead of https://github.com/jcmoraisjr/haproxy-ingress/pull/693

### CODE REVIEW

**Comment by jcmoraisjr** [comment]
Thanks for the contribution and also for the provided test!

I just realized that the current test can be extended to explore the wildcard scenario, what about add these new testcases in the array? You can use a distinct secret/crt changing the input accordingly and adding the new one in the cache mock.

**Comment by pbabilas** [comment]
You are right! Changes just commited.

**Comment by jcmoraisjr** [comment]
Finally travis released this, lgtm, thanks! Merging.

**Comment by pbabilas** [comment]
ok, so when new version with docker image will be released? :)

**Comment by jcmoraisjr** [comment]
v0.11 before the weekend, v0.10 and hope v0.12 next week, v0.9 this year.

**Comment by pbabilas** [comment]
gr8! waiting ;]

**Pull request merged**
