### PR TITLE
Independently configure rules and TLS

### PR DESCRIPTION
**Pull request by jcmoraisjr**
Since the very first controller version, the TLS spec was only configured if a corresponding hostname was found in the rules of the same ingress resource. This commit changes this behavior and reads the TLS array as an independent configuration.

Such update changes backward compatibility since a misconfigured TLS would be silently ignored. However the new behavior better implements the ingress spec.

### CODE REVIEW

**Comment by jcmoraisjr** [comment]
#669

**Comment by Unichron** [comment]
Hi,

Thank you so much for picking this up! I have a question though. Would it be possible to include annotation processing as well when only TLS is configured? Technically a decent part of the annotations configure TLS behavior. This would remove sooo much complexity for us.

**Comment by jcmoraisjr** [comment]
> Would it be possible to include annotation processing as well when only TLS is configured?

Yup, this is exactly how it should work - no matter where you configured a hostname, either in rules or just in tls, they should be added to the configuration in the same way.

**Comment by Unichron** [comment]
Ah sorry I missed the part where you added that line. Thank you!

**Pull request merged**
