### PR TITLE
HSTS and HTTPS redirect for case when SSL is terminated at the load balancer

### PR DESCRIPTION
**Pull request by idubrov**
Follow-up pull request for #38 

I don't like that I had to copy the whole httpfront section.

Also, this new https2httpfront only loop over non-HTTPS servers -- not sure if this is correct (although in this mode HTTPS servers are sort of useless anyway as we terminate SSL before getting to HAProxy).

Any comments/suggestions? Makes sense/does not?

### CODE REVIEW

**Comment by jcmoraisjr** [comment]
This does make sense, yes. I'm fine with the proposal but I wouldn't like to support another duplication on the template. Let me think a few more time about this (for 1..2? include/import? ...?). New ideas are very welcome.

**Comment by idubrov** [comment]
Another option I was considering is to

 * Always send HSTS on port 80 (browser would ignore it if received via HTTP)
 * Make :81 to be "redirect" port that will always send traffic to https

In this case, the configuration would be inverse, HTTP would go to 81 to get redirect and HTTPS would go to 80.

However, I don't like two things here:
 * Sending HSTS over HTTP is sort of untidy. You can check X-Forwarded-Proto, but with TCP backend AWS ELB does not send X-Forwarded-Proto.
 * No control over which HTTP traffic gets redirected (it's all or nothing). In the implementation I submitted it (should, anyway :) ) work in a way that it redirects only if a) global force-ssl-redirect is set to true b) per-ingress annotation ingress.kubernetes.io/force-ssl-redirect is set to true

**Comment by jcmoraisjr** [comment]
Is there any difference in headers between HTTP and HTTPS requests? If so the same listener could handle both requests, changing the behavior with ACL - and inside an annotation saying "I'm behind a LB".

**Comment by idubrov** [comment]
If load balancer uses HTTP protocol to the backend, it sets X-Forwarded-Proto header to either http/https.

However, with PROXY protocol (TCP backend in AWS ELB), there is no difference -- requests are exactly the same.

**Comment by idubrov** [comment]
If AWS load balancer uses HTTP protocol to the backend, it sets X-Forwarded-Proto to indicate original scheme (it's either "http" or "https"). 

However, if ELB uses TCP protocol to the backend (PROXY protocol), there is no difference, requests are exactly the same.

**Comment by ColDog** [comment]
Any updates on this PR? I'm very interested in the solution to this issue, if you need a hand testing or writing I'm interested in helping.

**Comment by idubrov** [comment]
@ColDog check #38. It seems like it would solve that issue (I haven't tried it myself, though).

**Pull request closed without merging**
